yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
    path('contact_us', views.AboutContactUsVies.as_view(), name='contact_us'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'user_profile/',
        views.UserProfileView.as_view(),
        name='user_profile',
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html',
            success_url=reverse_lazy('users:password_change_done')
        ),
        name='password_change'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            success_url=reverse_lazy('users:password_reset_done')
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:password_reset_complete')
        ),
        name='password_reset_confirm'
    )
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/templates/includes/footer.html
{% load static %}
{% load posts_tags %}

<div class="pre-footer"></div>
{% popular_articles request=request %}
<div class="my-footer-decorated">
  <div class="my-footer-decorated__decorated-line"></div>
  <section class="my-footer">
    <div class="my-footer__columns">
      <div class="my-footer__column my-footer__column_content_copyright">
        <div class="ya-logo"></div>
        <div class="logo-copyright">
          <div class="logo">
            <strong>Я</strong><span class="logo_decorated">Писарь</span>
          </div>
          <p class="my-copyright">&copy; {{ year }}.</p>
        </div>
      </div>
      <div class="my-footer__column my-footer__column_content_info">
        <h2 class="my-footer__column-heading">О проекте</h2>
        <nav class="my-footer__column-links">
          <a 
            class="my-footer__column-link"
            href="{% url 'about:tech' %}">
            Технологии
          </a>
          <a 
            class="my-footer__column-link" 
            href="{% url 'about:author' %}">
            Об авторе
          </a>
          <a 
            class="my-footer__column-link" 
            href="{% url 'about:contact_us' %}">
            Связаться
          </a>
        </nav>
      </div>
      <div class="my-footer__column my-footer__column_content_social">
        <h2 class="my-footer__column-heading">Соцсети</h2>
        <nav class="my-footer__column-links">
          <a
            class="my-footer__column-link"
            href="https://facebook.com/"
            target="_blank">
            <img
              class="my-footer__social-icon"
              src="{% static 'images/facebook_color_white.svg' %}" 
              alt="">
            Facebook
          </a>
          <a
            class="my-footer__column-link"
            href="https://vk.com/"
            target="_blank">
            <img
              class="my-footer__social-icon"
              src="{% static 'images/vk_color_white.svg' %}"
              alt="">
            ВКонтакте
          </a>
          <a
            class="my-footer__column-link"
            href="https://instagram.com/"
            target="_blank">
            <img
              class="my-footer__social-icon"
              src="{% static 'images/instagram_color_white.svg' %}"
              alt="">
            Instagram
          </a>
        </nav>
      </div>
    </div>
  </section>
</div>

yatube/templates/includes/form_errors.html
{% if form.errors %}
  {% for error in form.non_field_errors %}
    <div class="text-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}

yatube/templates/includes/form_fields.html
{% load user_filters %}
{% csrf_token %}
{% for field in form %}
  <div class="my-row">
    <label for="{{ field.id_for_label }}" class="label-form">
      {{ field.label }}
      {% if field.field.required %}
        <span class="text-danger">*</span>
      {% endif %}
    </label>    
    {{ field }}
    {% if field.help_text %}
      <small 
        id="{{ field.id_for_label }}-help" 
        class="form-text">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
    {% if field.errors %}
      {% for error in field.errors %}            
        <div class="text-danger">
          {{ error|escape }}
        </div>
      {% endfor %}
    {% endif %}
  </div>
{% endfor %}

yatube/templates/includes/sidebar.html
{% with request.resolver_match.view_name as view_name %}
  <div id="sidebar">
    <div class="inner">
      <!-- Search -->
      <section id="search" class="alt">
        <form method="get" action="/search/">
          <input type="text" name="query" id="query" placeholder="Найти"/>
        </form>
      </section>

      <!-- Menu -->
      <nav id="menu">
        <header class="major">
          <div class="logo">
            <strong>Я</strong><span class="logo_decorated">Писарь</span>
          </div>
        </header>
        <ul>
          <li>
            <a
            {% if view_name  == 'posts:index' %}
              class="active-menu-item"
            {% endif %} 
              href="{% url 'posts:index' %}">
              Главная
            </a>
          </li>
          {% if user.is_authenticated %}
            <li>
              <a 
                {% if view_name  == 'posts:follow_index' %}
                  class="active-menu-item"
                {% endif %}
                href="{% url 'posts:follow_index' %}">
                Избранное
              </a>
            </li>
            <li>
              <a 
                {% if view_name  == 'posts:authors' %}
                  class="active-menu-item"
                {% endif %}
                href="{% url 'posts:authors' %}">
                Авторы
              </a>
            </li>
            <li>
              <a
                {% if view_name  == 'posts:post_create' %}
                  class="active-menu-item"
                {% endif %} 
                href="{% url 'posts:post_create' %}">
                Новая запись
              </a>
            </li>
            <li>
              <a
                {% if view_name  == 'users:user_profile' %}
                  class="active-menu-item"
                {% endif %} 
                href="{% url 'users:user_profile' %}">
                Профиль
              </a>
            </li>
            <li>
              <a href="{% url 'users:logout' %}">
                Выйти
              </a>
            </li>
          {% else %}
            <li>
              <a 
                {% if view_name  == 'posts:authors' %}
                  class="active-menu-item"
                {% endif %}
                href="{% url 'posts:authors' %}">
                Авторы
              </a>
            </li>
            <li>
              <a href="{% url 'users:login' %}">
                Войти
              </a>
            </li>
            <li>
              <a href="{% url 'users:signup' %}">
                Регистрация
              </a>
            </li>
          {% endif %}  
        </ul>
      </nav>

    </div>
  </div>
{% endwith %}