yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
    path('contact_us', views.AboutContactUsVies.as_view(), name='contact_us'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path(
        'group/empty_group/',
        views.GroupPosts.as_view(),
        name='posts_without_group'
    ),
    path('group/<slug:slug>/', views.GroupPosts.as_view(), name='group_list'),
    path('profile/<str:username>/', views.Profile.as_view(), name='profile'),
    path('create/', views.PostCreate.as_view(), name='post_create'),
    path(
        'posts/<int:post_id>/edit/',
        views.PostEdit.as_view(),
        name='post_edit'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.AddComment.as_view(),
        name='add_comment'
    ),
    path(
        'posts/<int:post_id>/',
        views.PostDetail.as_view(),
        name='post_detail'
    ),
    path('follow/', views.FollowIndex.as_view(), name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.ProfileFollow.as_view(),
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.ProfileUnfollow.as_view(),
        name='profile_unfollow'
    ),
    path('authors/', views.ListAuthors.as_view(), name='authors'),
    path('search/', views.Search.as_view(), name='search'),
    path('posts/<int:post_id>/like/', views.PostLike.as_view(), name='like'),
    path(
        'followers/<str:username>/',
        views.ListFollowers.as_view(),
        name='list_followers'),
    path(
        'followings/<str:username>/',
        views.ListFollowings.as_view(),
        name='list_followings'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.constraints import UniqueConstraint
from django.urls import reverse_lazy

SLUG_HELP_TEXT = (
    'Может содержать символы английского алфавита цифры и символы: "_", "-".'
)
PATH_POSTS_IMAGE = getattr(settings, 'PATH_POSTS_IMAGE', 'posts/')

User = get_user_model()


class Post(models.Model):
    title = models.CharField('Заголовок', max_length=60)
    text = models.TextField(
        'Содержимое поста',
        help_text='Введите текст записи'
    )
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу'
    )
    image = models.ImageField(
        'Картинка',
        upload_to=PATH_POSTS_IMAGE,
        blank=True
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

    def __str__(self):
        return self.text[:15]

    def get_absolute_url(self):
        return reverse_lazy('posts:post_detail', kwargs={'post_id': self.id})


class Group(models.Model):
    title = models.CharField('Заголовок', max_length=200)
    slug = models.SlugField(
        'Идентификатор',
        unique=True,
        help_text=SLUG_HELP_TEXT
    )
    description = models.TextField('Описание')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Запись'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(
        'Комментарий'
    )
    created = models.DateTimeField('Дата добавления', auto_now_add=True)

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        constraints = (
            UniqueConstraint(
                fields=('user', 'author',),
                name='unique_follow'
            ),
        )
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'


class Like(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='likes',
        verbose_name='Пользователь'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='likes',
        verbose_name='Запись'
    )

    class Meta:
        constraints = (
            UniqueConstraint(
                fields=('user', 'post',),
                name='unique_like'
            ),
        )
        verbose_name = 'Симпотка'
        verbose_name_plural = 'Симпотки'

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text', 'group', 'image')


class CommentForm(forms.ModelForm):
    text = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'placeholder': 'Текст комментария',
                'rows': '6',
            }
        )
    )

    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.db.models import Count, Q, Subquery
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, View

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Like, Post, User
from .utils import (AuthorsListMixin, PostAuthorEqualUserMixin, PostListMixin,
                    queryset_cur_user_comments, queryset_cur_user_likes,
                    queryset_user_followers, queryset_user_followings)

TEMPLATE_POST_CREATE = 'posts/create_post.html'


class Index(PostListMixin, ListView):
    template_name = 'posts/index.html'

    def get_queryset(self):
        cache_key = f'index_{self.request.user.username}'
        queryset = cache.get(cache_key)
        if queryset:
            return queryset
        q_cur_user_likes = queryset_cur_user_likes(self.request)
        q_cur_user_comments = queryset_cur_user_comments(self.request)
        queryset = Post.objects.select_related(
            'group', 'author'
        ).prefetch_related(
            'likes', 'comments'
        ).annotate(
            cur_user_like=Subquery(
                q_cur_user_likes.values('user')[:1]
            )
        ).annotate(
            cur_user_comment=Subquery(
                q_cur_user_comments.values('author')[:1]
            )
        )
        queryset = list(queryset)
        cache.set(cache_key, queryset, 20)
        return queryset


class Search(PostListMixin, ListView):
    template_name = 'posts/search.html'

    def get_queryset(self):
        self.query = self.request.GET.get('query')
        q_cur_user_likes = queryset_cur_user_likes(self.request)
        q_cur_user_comments = queryset_cur_user_comments(self.request)
        return Post.objects.select_related(
            'author', 'group'
        ).prefetch_related(
            'likes', 'comments'
        ).filter(
            Q(text__icontains=self.query) | Q(title__icontains=self.query)
        ).annotate(
            cur_user_like=Subquery(
                q_cur_user_likes.values('user')[:1]
            )
        ).annotate(
            cur_user_comment=Subquery(
                q_cur_user_comments.values('author')[:1]
            )
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.query
        return context


class GroupPosts(PostListMixin, ListView):
    template_name = 'posts/group_list.html'

    def get_queryset(self):
        slug = self.kwargs.get('slug')
        self.group = slug and get_object_or_404(Group, slug=slug)
        q_cur_user_likes = queryset_cur_user_likes(self.request)
        q_cur_user_comments = queryset_cur_user_comments(self.request)
        return Post.objects.select_related(
            'author'
        ).prefetch_related(
            'likes', 'comments'
        ).filter(
            group=self.group
        ).annotate(
            cur_user_like=Subquery(
                q_cur_user_likes.values('user')[:1]
            )
        ).annotate(
            cur_user_comment=Subquery(
                q_cur_user_comments.values('author')[:1]
            )
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['group'] = self.group
        return context


class Profile(PostListMixin, ListView):
    template_name = 'posts/profile.html'

    def get_queryset(self):
        self.author = get_object_or_404(User, username=self.kwargs['username'])
        q_cur_user_likes = queryset_cur_user_likes(self.request)
        q_cur_user_comments = queryset_cur_user_comments(self.request)
        return self.author.posts.select_related(
            'group'
        ).prefetch_related(
            'likes', 'comments'
        ).annotate(
            count_posts=Count('id')
        ).annotate(
            cur_user_like=Subquery(
                q_cur_user_likes.values('user')[:1]
            )
        ).annotate(
            cur_user_comment=Subquery(
                q_cur_user_comments.values('author')[:1]
            )
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = self.author
        context['following'] = self.author.following.filter(
            user_id=self.request.user.id
        ).exists()
        return context


class PostDetail(View):
    def get(self, request, post_id):
        post = get_object_or_404(Post, pk=post_id)
        post.cur_user_like = Like.objects.filter(
            user__username=request.user.username,
            post=post
        ).exists()
        post.cur_user_comment = Comment.objects.filter(
            author__username=request.user.username,
            post=post
        ).exists()
        form = CommentForm()
        context = {
            'post': post,
            'form': form,
        }
        return render(request, 'posts/post_detail.html', context)


class PostCreate(LoginRequiredMixin, CreateView):
    form_class = PostForm
    template_name = TEMPLATE_POST_CREATE

    def get_success_url(self):
        return reverse_lazy(
            'posts:profile',
            args=(self.request.user.username,)
        )

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostEdit(LoginRequiredMixin, PostAuthorEqualUserMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = TEMPLATE_POST_CREATE
    pk_url_kwarg = 'post_id'

    def get_success_url(self):
        return reverse_lazy(
            'posts:post_detail',
            args=(self.kwargs['post_id'],)
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_edit'] = True
        return context


class AddComment(LoginRequiredMixin, View):
    def post(self, request, post_id):
        post = get_object_or_404(Post, pk=post_id)
        form = CommentForm(request.POST or None)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
        return redirect('posts:post_detail', post_id=post_id)


class FollowIndex(LoginRequiredMixin, PostListMixin, ListView):
    template_name = 'posts/follow.html'

    def get_queryset(self):
        q_cur_user_likes = queryset_cur_user_likes(self.request)
        q_cur_user_comments = queryset_cur_user_comments(self.request)
        return Post.objects.filter(
            author__following__user=self.request.user
        ).select_related(
            'author', 'group'
        ).prefetch_related(
            'likes', 'comments'
        ).annotate(
            cur_user_like=Subquery(
                q_cur_user_likes.values('user')[:1]
            )
        ).annotate(
            cur_user_comment=Subquery(
                q_cur_user_comments.values('author')[:1]
            )
        )


class ProfileFollow(LoginRequiredMixin, View):
    def get(self, request, username):
        author = get_object_or_404(User, username=username)
        follow_exist = author.following.filter(
            user_id=request.user.id
        ).exists()
        if (author != request.user and not follow_exist):
            Follow.objects.create(user=request.user, author=author)
        return redirect(
            reverse_lazy(
                'posts:profile',
                args=(author.username,)
            )
        )


class ProfileUnfollow(LoginRequiredMixin, View):
    def get(self, request, username):
        follows = Follow.objects.filter(
            user=request.user,
            author__username=username,
        )
        if follows.exists():
            follows.delete()
        return redirect(
            reverse_lazy(
                'posts:profile',
                args=(username,)
            )
        )


class ListAuthors(AuthorsListMixin, ListView):
    q_user_followers = queryset_user_followers()
    q_user_followings = queryset_user_followings()
    queryset = User.objects.annotate(
        posts_count=Count('posts')
    ).filter(
        posts_count__gt=0
    ).prefetch_related(
        'profile'
    ).annotate(
        follower__count=Subquery(
            q_user_followers.values('follower__count')[:1]
        ),
        following__count=Subquery(
            q_user_followings.values('following__count')[:1]
        )
    )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Список авторов'
        return context


class ListFollowers(AuthorsListMixin, ListView):
    def get_queryset(self):
        username = self.kwargs['username']
        self.subject = get_object_or_404(User, username=username)
        q_user_followers = queryset_user_followers()
        q_user_followings = queryset_user_followings()
        followers = Follow.objects.filter(
            author__username=username
        ).values('user')
        return User.objects.annotate(
            posts_count=Count('posts')
        ).filter(
            pk__in=followers
        ).prefetch_related(
            'profile'
        ).annotate(
            follower__count=Subquery(
                q_user_followers.values('follower__count')[:1]
            ),
            following__count=Subquery(
                q_user_followings.values('following__count')[:1]
            )
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Подписчики: '
        context['subject'] = self.subject
        return context


class ListFollowings(AuthorsListMixin, ListView):
    def get_queryset(self):
        username = self.kwargs['username']

yatube/templates/posts/includes/article.html
{% load thumbnail %}
{% load static %}
{% load user_filters %}


<div class="col-6 col-12-narrower">
  <section class="box-alpha special">
    <span class="image featured article-middle-container">
      {% if post.image %}
        {% thumbnail post.image "576x256" crop="center" upscale=True as im %}
          <img 
            src="{{ im.url }}" 
            alt="" 
            class="article-middle-container__image">
        {% endthumbnail %}
      {% else %}
        <img 
          src="{% static 'images/pic_alpha02.jpg' %}" 
          alt="" 
          class="article-middle-container__image">
      {% endif %}   
      <div class="article-middle">
        <time class="article-middle__time">
          <strong>{{ post.pub_date|date:"d.m.Y" }}</strong>
        </time>
        <p class="article-middle__label">
          <strong>Автор:</strong>
        </p>
        <a 
          class="article-middle__link" 
          href="{% url 'posts:profile' username=post.author.username %}">
          {{ post.author|user_repr }}
        </a>
        <p class="article-middle__label">
          <strong>Группа:</strong>
        </p>
        {% if post.group %}
          {% url "posts:group_list" slug=post.group.slug  as the_url %}
        {% else %}
          {% url "posts:posts_without_group" as the_url %}
        {% endif %}
        <a 
          class="article-middle__link" 
          href="{{ the_url }}">
          {{ post.group.title|default:"---------" }}
        </a>
        <ul class="article-middle__stats">
          <li class="article-middle__stats-item">
            <a 
              href="{% url 'posts:like' post_id=post.pk %}"
              class="{{ post|current_user_like }}"
              id="article_heart_{{ post.pk }}">
              {{ post.likes.count }}
            </a>
          </li>
          <li class="article-middle__stats-item">
            <a 
              href="{% url 'posts:post_detail' post_id=post.pk %}#article-comments"
              class="{{ post|current_user_comment }}">
              {{ post.comments.count }}
            </a>
          </li>
        </ul>
      </div>
    </span>
    <h3 class="article-title-preview">
      {{ post.title}}
    </h3>
    <p class="article-text-preview">
      {{ post.text|truncatewords:20 }}
    </p>
    <ul class="actions special">
      <li>
        <a 
          href="{% url 'posts:post_detail' post_id=post.pk %}" 
          class="button alt">
          Читать полностью
        </a>
      </li>
    </ul>
  </section>
</div>

yatube/templates/posts/includes/author_card.html
{% load static %}
{% load user_filters %}
{% load thumbnail %}

<div class="author-card">
	<div class="author-card__name">
		<img 
			class="avatar avatar-80" 
			alt=""
			{% if author.profile.image %}
				{% thumbnail author.profile.image "80x80" crop="center" upscale=True as im %}
          src="{{ im.url }}"
        {% endthumbnail %}
      {% else %}
			  src="{% static 'images/pic12.jpg' %}"
      {% endif %}
		>
		<h5>
			{{ author|user_repr }}
		</h5>
	</div>
	<ul class="author-card__stats">
		<li class="author-card__stats-item">
			<a 
				href="{% url 'posts:list_followers' username=author.username %}" 
				class="author-card__stats-link">
				{% if author.following__count %}
					Подписчиков: {{ author.following__count }}
				{% else %}
					Подписчиков: {{ author.following.count }}
				{% endif %}
			</a>
		</li>
		<li class="author-card__stats-item">
			<a 
			href="{% url 'posts:list_followings' username=author.username %}"
				class="author-card__stats-link">
				{% if author.follower__count %}
					Подписан: {{ author.follower__count }}
				{% else %}
					Подписан: {{ author.follower.count }}
				{% endif %}
			</a>
		</li>
		<li class="author-card__stats-item">
			{% if request.resolver_match.view_name  == 'posts:profile' %}
			  Записей: {{ author.posts.count }}
      {% else %}
        <a 
          href="{% url 'posts:profile' username=author.username %}"
          class="author-card__stats-link">
          Записей: {{ author.posts.count }}
        </a>
      {% endif %}
		</li>
	</ul>
</div>

yatube/templates/posts/includes/comments.html
{% load user_filters %}

<ul class="article-comments__container">
  {% for comment in post.comments.all %}
    <li class="article-comments__item">
      <h5>
        <a
          class="comment-link" 
          href="{% url 'posts:profile' username=comment.author.username %}">
          {{ comment.author|user_repr }}
        </a>
      </h5>
      <p class="comment-text">
        {{ comment.text|linebreaksbr }}
      </p>
    </li>
  {% endfor %}
</ul>

yatube/templates/posts/includes/mini_article.html
{% load static %}
{% load user_filters %}
{% load thumbnail %}

<li class="mini-card module">
  <time>
    <strong> Запись </strong>
    от  {{ pop_post.pub_date|date:"d.m.Y" }}
  </time>
  <h3 class="mini-card-title">
    <a 
      href="{% url 'posts:post_detail' post_id=pop_post.pk %}">
      {{ pop_post.title }}
    </a>
  </h3>
  <div class="tags">
    {% if pop_post.group %}
      {% url "posts:group_list" slug=pop_post.group.slug  as the_url %}
    {% else %}
      {% url "posts:posts_without_group" as the_url %}
    {% endif %}
    <a href="{{ the_url }}">
      {{ pop_post.group.title|default:"---------" }}
    </a>
  </div>
  <div class="author-row">
    <a
      href="{% url 'posts:profile' username=pop_post.author.username %}">
      {% if pop_post.author.profile.image %}
        {% thumbnail pop_post.author.profile.image "80x80" crop="center" upscale=True as im %}
          <img 
                src="{{ im.url }}" 
                alt="" 
                class="avatar avatar-80">
        {% endthumbnail %}
      {% else %}
        <img
          alt=""
          src="{% static 'images/pic12.jpg' %}"
          class="avatar avatar-80">
      {% endif %}
    </a>
    <a 
      class="author-name" 
      href="{% url 'posts:profile' username=pop_post.author.username %}">
      {{ pop_post.author|user_repr }}
    </a>
  </div>
</li>

yatube/templates/posts/includes/paginator.html
{% if page_obj.has_other_pages %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li>
        <a class="button btn-paginator" href="?page=1">Первая</a>
      </li>
      <li>
        <a class="button" href="?page={{ page_obj.previous_page_number }}">
          &lt;&lt;
        </a>
      </li>
    {% else %}
      <li>
        <span class="button disabled btn-paginator">
            Первая
        </span>
      </li>
      <li>
        <span class="button disabled">
          &lt;&lt;
        </span>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
      <li>  
        {% if page_obj.number == i %}
            <span class="page active">{{ i }}</span>
        {% elif i >= page_obj.number|add:-2 and i <= page_obj.number|add:2 %}
            <a class="page" href="?page={{ i }}">{{ i }}</a>
        {% endif %}
      </li>
    {% endfor %}
    {% if page_obj.has_next %}
      <li>
        <a class="button" href="?page={{ page_obj.next_page_number }}">
          &gt;&gt;
        </a>
      </li>
      <li>
        <a class="button btn-paginator" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% else %}
      <li>
        <span class="button disabled">
          &gt;&gt;
        </span>
      </li>
      <li>
        <span class="button disabled btn-paginator">
          Последняя
        </span>
      </li>
    {% endif %}    
  </ul>
{% endif %}