yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
    path('contact_us', views.AboutContactUsVies.as_view(), name='contact_us'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'user_profile/',
        views.UserProfileView.as_view(),
        name='user_profile',
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html',
            success_url=reverse_lazy('users:password_change_done')
        ),
        name='password_change'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
            success_url=reverse_lazy('users:password_reset_done')
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:password_reset_complete')
        ),
        name='password_reset_confirm'
    )
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/users/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

User = get_user_model()

THEME_CHOICES = (
    ('light-theme.css', 'Светлая'),
    ('dark-theme', 'Тёмная'),
)
PATH_PROFILE_IMAGE = getattr(settings, 'PATH_PROFILE_IMAGE', 'profiles/')


class UserProfile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile',
        verbose_name='Пользователь'
    )
    use_pop_article = models.BooleanField(
        default=True,
        verbose_name='Отображать популярные записи'
    )
    theme = models.CharField(
        max_length=100,
        choices=THEME_CHOICES,
        default=THEME_CHOICES[0][0],
        verbose_name='Тема'
    )
    image = models.ImageField(
        'Картинка профиля',
        upload_to=PATH_PROFILE_IMAGE,
        blank=True
    )


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    if not UserProfile.objects.filter(user=instance).exists():
        UserProfile.objects.create(user=instance)

yatube/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from .models import UserProfile

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('image', 'theme', 'use_pop_article')

yatube/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, View

from .forms import CreationForm, UserProfileForm
from .models import UserProfile
from .utils import set_session_user_profile


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'


class UserProfileView(LoginRequiredMixin, View):
    def get(self, request):
        profile = get_object_or_404(UserProfile, user=request.user)
        form = UserProfileForm(instance=profile)
        return render(
            request,
            'users/user_profile.html',
            {
                'form': form,
                'profile': profile
            }
        )

    def post(self, request):
        profile = get_object_or_404(UserProfile, user=request.user)
        form = UserProfileForm(
            request.POST or None,
            instance=profile,
            files=request.FILES or None
        )
        if form.is_valid():
            new_profile = form.save()
            set_session_user_profile(request, new_profile)
            cache_key = f'index_{self.request.user.username}'
            cache.delete(cache_key)
            return redirect('posts:index')
        return render(
            request,
            'users/user_profile.html',
            {
                'form': form,
                'profile': profile
            }
        )

yatube/templates/users/logged_out.html
{% extends "base.html" %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<header id="header">
  <h1 class="title"><strong>Вы вышли из системы</strong></h1>
</header>
<section id="main-alpha" class="my-container">
  <div class="my-box">
    <p class="text-center tall-text">
      Вы вышли из своей учётной записи. Ждём вас снова!
    </p>
  </div>
</section>
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменён{% endblock %}
{% block content %}
    {% include "users/includes/done_action.html" with source="change_done" %}
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
  <header id="header">
    <h1 class="title"><strong>Изменить пароль</strong></h1>
  </header>
  <section id="main-alpha" class="my-container">
    <form 
      class="my-box my-form"
      method="post" 
      action="{% url 'users:password_change' %}">
      {% csrf_token %}
      {% include "includes/form_errors.html" %}
      <div class="my-row">
        <label for="id_old_password" class="label-form">
          Старый пароль
          <span class="text-danger">*</span>
        </label>
        <input 
          type="password"
          name="old_password"
          autofocus 
          required 
          id="id_old_password">
      </div> 
      <div class="my-row">
        <label for="id_new_password1" class="label-form">
          Новый пароль
          <span class="text-danger">*</span>
        </label>
        <input 
          type="password" 
          name="new_password1" 
          required 
          id="id_new_password1"> 
        <small id="id_new_password1-help" class="form-text">
          <ul class="form-list">
            <li class="form-list__item">
              Ваш пароль не должен совпадать с вашим именем или 
              другой персональной информацией или быть слишком 
              похожим на неё.
            </li>
            <li class="form-list__item">
              Ваш пароль должен содержать как минимум 8 символов.
            </li>
            <li class="form-list__item">
              Ваш пароль не может быть одним из широко 
              распространённых паролей.
            </li>
            <li class="form-list__item">
              Ваш пароль не может состоять только из цифр.
            </li>
          </ul>
        </small>
      </div>
      <div class="my-row">
        <label for="id_new_password2" class="label-form">
          Подтверждение нового пароля
          <span class="required text-danger">*</span>
        </label> 
        <input type="password" 
          name="new_password2"
          required id="id_new_password2">
      </div>
      <div class="my-row">
        <button type="submit" class="button">Изменить пароль</button>
      </div>
    </form>
  </section>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
    {% include "users/includes/done_action.html" with source="reset_complete" %}
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
  {% if validlink %}
    <header id="header">
      <h1 class="title"><strong>Введите новый пароль</strong></h1>
    </header>
    <section id="main-alpha" class="my-container">
      <form 
        class="my-box my-form"
        method="post">
        {% csrf_token %}
        {% include "includes/form_errors.html" %}
        <div class="my-row">
          <label for="id_new_password1" class="label-form">
            Новый пароль
            <span class="text-danger">*</span>
          </label>
          <input 
            type="password" 
            name="new_password1" 
            required 
            id="id_new_password1"> 
          <small id="id_new_password1-help" class="form-text">
            <ul class="form-list">
              <li class="form-list__item">
                Ваш пароль не должен совпадать с вашим именем или 
                другой персональной информацией или быть слишком 
                похожим на неё.
              </li>
              <li class="form-list__item">
                Ваш пароль должен содержать как минимум 8 символов.
              </li>
              <li class="form-list__item">
                Ваш пароль не может быть одним из широко 
                распространённых паролей.
              </li>
              <li class="form-list__item">
                Ваш пароль не может состоять только из цифр.
              </li>
            </ul>
          </small>
        </div>
        <div class="my-row">
          <label for="id_new_password2" class="label-form">
            Подтверждение нового пароля        
            <span class="text-danger">*</span>        
          </label>
          <input type="password"
            name="new_password2"
            required id="id_new_password2">      
        </div>
        <div class="my-row">
          <button type="submit" class="button">Назначить новый пароль</button>
        </div> 
      </form>
    </section>
  {% else %}
    {% include "users/includes/done_action.html" with source="wrong_link" %}
  {% endif %}
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Отправлено письмо{% endblock %}
{% block content %}
  {% include "users/includes/done_action.html" with source="reset_done" %}
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
  <header id="header">
    <h1 class="title"><strong>Сброс пароля</strong></h1>
  </header>
  <section id="main-alpha" class="my-container">
    <div class="my-box">
      <p>
        Чтобы сбросить старый пароль — введите адрес электронной 
        почты, под которым вы регистрировались
      </p>
      <form 
        method="post" 
        action="{% url 'users:password_reset' %}">
        {% csrf_token %}
        <div class="my-row">
          <label for="id_email" class="label-form">
            Адрес электронной почты
            <span class="text-danger">*</span>
          </label>
          <input type="email"
            name="email"
            maxlength="254"
            required id="id_email">
        </div>
        <div class="my-row">
          <button type="submit" class="button">Сбросить пароль</button>
        </div>
      </form>
    </div>
  </section>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Регистрация{% endblock %}
{% block content %}
  <header id="header">
    <h1 class="title"><strong>Регистрация</strong></h1>
  </header>
  <section id="main-alpha" class="my-container">
    <form 
      class="my-box my-form"
      method="post" 
      action="{% url 'users:signup' %}">
      {% include "includes/form_errors.html" %}
      {% include "includes/form_fields.html" %}
      <div class="my-row">
        <button type="submit" class="button">Зарегистрироваться</button>
      </div>
    </form>
  </section>
{% endblock %} 

yatube/templates/users/user_profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% load user_filters %}
{% load static %}

{% block title %}
  Профиль: {{ user|user_repr }}
{% endblock %}

{% block content %}
  <header id="header">
    <h1 class="title">
      <strong>Профиль: </strong>
      {{ user|user_repr }}
    </h1>
  </header>
  <section id="main-alpha" class="my-container">
    <form 
      class="my-box my-form"
      method="post"
      enctype="multipart/form-data">
      {% csrf_token %}
      {% if profile.image %}
        {% thumbnail profile.image "256x256" crop="center" upscale=True as im %}
          <img class="profile-img" src="{{ im.url }}" alt="">
        {% endthumbnail %}
      {% else %}
        <img class="profile-img" src="{% static 'images/pic12.jpg' %}" alt="">
      {% endif %}
      {% include "includes/form_errors.html" %}
      {% for field in form %}
        <div class="my-row"
          {% if field.field.required %} 
            aria-required="true"
          {% else %}
            aria-required="false"
          {% endif %}>
          {% if field.name == 'use_pop_article' %}
            {{ field }}
          {% endif %}
          <label 
            for="{{ field.id_for_label }}" 
            class="label-form">
            {{ field.label }}
            {% if field.field.required %}
              <span class="text-danger">*</span>
            {% endif %}
          </label>
          {% if field.name != 'use_pop_article' %}
            {{ field }}
          {% endif %}
          {% if field.help_text %}
            <small id="{{ field.id_for_label }}-help" 
              class="form-text">
              {{ field.help_text|safe }}
            </small>
          {% endif %}
        </div>
      {% endfor %}
      <div class="my-row">
        <button type="submit" class="button">Сохранить</button>
        <a 
          href="{% url 'password_change' %}" 
          class="my-link">
          Сменить пароль
        </a>
      </div>
    </form>
  </section>
{% endblock %}